name: hulajuan
description: Flutter project inspired by the game Pinoy Henyo.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HulaJuan 1st-party packages.
  hulajuan_core:
    path: packages/hulajuan_core
  hulajuan_ui:
    path: packages/hulajuan_ui
  words_repository:
    path: packages/words_repository   
     
  # 3rd party packages.
  bloc: ^8.1.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  package_info_plus: ^1.4.3+1
  path_provider: ^2.0.11
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Gugi
      fonts:
        - asset: assets/fonts/Gugi-Regular.ttf

flutter_icons:
  android: true
  adaptive_icon_background: "#ffffff"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48
  