name: words_repository
description: App package that handles words domain.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  json_annotation: ^4.7.0
  meta: ^1.3.0

dev_dependencies:
  build_runner: ^2.0.0
  coverage: ^1.1.0
  json_serializable: ^6.5.4
  mocktail: ^0.2.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0
