name: hulajuan_ui
description: UI toolkit for HulaJuan app.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  bloc: ^8.1.0
  bouncing_widget: ^2.0.0
  equatable: ^2.0.3
  flex_color_scheme: ^6.0.1
  hydrated_bloc: ^9.0.0

dev_dependencies:
  coverage: ^1.1.0
  mocktail: ^0.2.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0
